# Generated by Django 5.0.1 on 2024-01-14 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reto.evento'),
        ),
    ]
