# Generated by Django 4.2.3 on 2024-01-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0002_participante_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ciudad',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
