# Generated by Django 4.2.3 on 2024-01-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0003_participante_ciudad_participante_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='tieneci',
            field=models.IntegerField(null=True),
        ),
    ]
