# Generated by Django 4.2.3 on 2024-01-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0004_participante_tieneci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='edad',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='tieneci',
            field=models.BooleanField(null=True),
        ),
    ]
