# Generated by Django 4.2.3 on 2024-01-19 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0005_alter_participante_edad_alter_participante_tieneci'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reto.evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='participacion',
            field=models.CharField(choices=[('unico_evento', 'Único evento'), ('unico_dia', 'Único por día'), ('unico_semana', 'Único por semana'), ('unico_mes', 'Único por mes')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='record',
            field=models.CharField(choices=[('puntaje', 'Puntaje'), ('tiempo', 'Tiempo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tiene_categoria',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tiene_subcategoria',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reto.categoria'),
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15)),
                ('ciudad', models.CharField(max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('parentezco', models.CharField(max_length=100)),
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reto.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('marca', models.IntegerField(null=True)),
                ('tiempo', models.TimeField(null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reto.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reto.evento')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reto.participante')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reto.subcategoria')),
            ],
        ),
    ]
