# Generated by Django 5.0.1 on 2024-01-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0006_categoria_evento_evento_participacion_evento_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ultima_participacion',
            field=models.DateTimeField(null=True),
        ),
    ]
