# Generated by Django 5.0.1 on 2024-01-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0007_participante_ultima_participacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='evento',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='subcategoria',
        ),
    ]
