# Generated by Django 5.0.1 on 2024-01-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0008_remove_participante_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='usuario',
        ),
    ]
