# Generated by Django 4.2.3 on 2024-01-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reto', '0009_remove_participante_edad_remove_participante_puntos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntaje',
            name='tiempo',
        ),
    ]
